<meta charset="utf8">
<?php
//ob_start();
session_start();
?>
<?php
$sId="nuk";
$sPwd="0000";
$uId=$_GET["uId"];//使用GET寫法較不安全，因為所輸入的東西會被直接顯示出來
//echo"你的帳號:".$uId."<br/>";
$uPwd=$_GET["uPwd"];
//echo"你的密碼:".$uPwd."<br/>";
if($sId==$uId&&$sPwd==$uPwd){
    $_SESSION["check"]="Yes";
    header("Location:info_im1.php");
}else{
    $_SESSION["check"]="No";
    header("Location:fail.php");//使用該寫法跳轉到不同的頁面
}
//ob_flush();//緩衝區
?>